language: node_js
node_js:
- '8'
- '9'
sudo: required
services:
- docker
before_install:
- docker run -p 6379:6379 -d --name redis redis:3.0.7-alpine
- docker run -d --hostname rabbit --name rabbit -p 8080:15672 -p 5672:5672 rabbitmq:3-management
script: npm run test:mutation
jobs:
  include:
  - stage: npm release
    node_js: '9'
    script: npm run build
    deploy:
      provider: npm
      email: thiago@cruxframework.org
      api_key:
        secure: R69iX1mlylutYsM4dDSO4WoBYeUEIOpvasuA/cDiWQs+d8KKqtd/tpFC/nhQ2Mri3lH95XG6Ko6SnCCAIw9STuD9fcbkjSIxRIQwFEJKSo9IX7dm2+WIOoC8H42Hpuazt0Ze+7gGaKu+zyWHDRbU3jLlpaVOG9dUZF4rXM39XNCwQRGwLBvopLsKBdnG5zfamCLdkzwYHBXHwtQcQcZYbtfjNXcx9BG88JHYgQz1KA9UYD9OstTSw0FF1PszMI8HLmKtOhj3fGDJMB8hFGQKXgPygdNakBpbW3ZUTmpRNwxLg9Hbsq0/imY1cTvmQ3Ji6R850o1h+Wg1gfOsTZIjwNFOT1aat/luW6vJZHeM+6vI9iWxooCJmgJbxFr613jSfxlNGdQXzH+2QOgZQIvOeBvDFLH85sPftvcvWsc9jm979VXToFALtgEe6qyEGzlyPZ31VlTfphhlfFAWJQVkt65RrZsvoyHIEwUJxkMgLg1eoCLa96tDd0TS3lOkxl/qBckrqUeu6Da4Vh1mZLKgukmQaFB9Sh0pNx+iE+NQV+nlP8pIyKbl+6z6cDBkBsPyc4OGeYfB5tNr2c1n/E7QRn2RtNBEGLqiy96DOvKpr8XDGWktbBcFEdPa2Hc4rq/dfzvxXWqmjBvuBGXrSxcOrK6G1JKsh7yxxs1uzhXQUmk=
      on:
        tags: true
        repo: thiagobustamante/node-eventstore
